### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by vol0da** [deweller/PHPCodeIntel#11]
Sublime is unable to load plugin because of unknown modules:

ImportError: No module named threadq

ImportError: No module named preferences

ImportError: No module named phpdaemon

**Comment by deweller** [comment]
I fixed this for Sublime Text 2.  Importing is broken in ST3, though.

**Comment by vol0da** [comment]
I made some changes [in my fork](https://github.com/vol0da/PHPCodeIntel) and it looks like everything is working however I don't know whether those changes are compatible with ST2
