### ISSUE TITLE
Trying to run PHP daemon independently from ST and Python

### ISSUE THREAD

**Issue by Alexey-T** [deweller/PHPCodeIntel#16]
Hello Devon, I appreciate your work started on ST2 forum.
Good work and good idea.

I want to use your PHP daemon in my freeware project SynWrite, and I need to know - how to start PHP daemon? I don;t know php much. So can u pls make instruction:

a) create such folder structure..........
b) copy php.exe + php5.dll + etc from PHP 5.x to this folder.........
c) run "php.exe phpdaemon.php [port_number]".........
d) etc

Can u help?
If daemon can be started, i then can use it from Delphi code

**Comment by deweller** [comment]
Sorry, but I can't help you with running this on a Windows platform.  I develop on Mac only.  

I wish you the best of luck in getting this to work in your project.
