### ISSUE TITLE
Example daemon command?

### ISSUE THREAD

**Issue by Alexey-T** [deweller/PHPCodeIntel#17]
Devon, can u show me example daemon command, to enter in browser, which can get autocompletion for any file.

I can run daemon on Windows.
for ex, I want to get autocompletion for file NN.php for line 10 and column 20.
`http://127.0.0.1:20001/..............` -- what to write in URL?

**Comment by deweller** [comment]
Sorry - I am not able to provide support for this project.  I recommend you read the code or experiment to figure out if can do what you need it to do.  Good luck.
